import { contextBridge, ipcRenderer, webUtils } from 'electron'
import type { LauncherApi, LauncherEvents } from '../shared/types'

const invoke = <T>(channel: string, ...args: unknown[]): Promise<T> => ipcRenderer.invoke(`launcher:${channel}`, ...args)

const api: LauncherApi = {
  getUpdate: () => invoke('get-update'),
  checkUpdate: () => invoke('check-update'),
  downloadUpdate: () => invoke('download-update'),
  cancelUpdate: () => invoke('cancel-update'),
  installUpdate: () => invoke('install-update'),
  setPresenceContext: context => invoke('set-presence-context', context),
  getDownloads: () => invoke('get-downloads'),
  controlDownloads: (action, id, beforeId) => invoke('control-downloads', action, id, beforeId),
  getModFavorites: refresh => invoke('get-mod-favorites', refresh),
  setModFavorite: (favorite, saved) => invoke('set-mod-favorite', favorite, saved),
  getState: () => invoke('get-state'),
  getVersions: refresh => invoke('get-versions', refresh),
  saveSettings: settings => invoke('save-settings', settings),
  chooseHeroBackgrounds: limit => invoke('choose-hero-backgrounds', limit),
  readHeroBackground: (id, thumbnail) => invoke('read-hero-background', id, thumbnail),
  saveProfile: profile => invoke('save-profile', profile),
  cloneProfile: id => invoke('clone-profile', id),
  exportProfile: id => invoke('export-profile', id),
  importProfile: path => invoke('import-profile', path),
  repairProfile: id => invoke('repair-profile', id),
  chooseProfileCover: () => invoke('choose-profile-cover'),
  chooseProfileIcon: () => invoke('choose-profile-icon'),
  saveProfileCover: (id, cover) => invoke('save-profile-cover', id, cover),
  getDroppedFilePath: file => webUtils.getPathForFile(file),
  deleteProfile: id => invoke('delete-profile', id),
  reorderProfiles: ids => invoke('reorder-profiles', ids),
  selectProfile: id => invoke('select-profile', id),
  selectVersion: id => invoke('select-version', id),
  selectAccount: id => invoke('select-account', id),
  createOfflineAccount: name => invoke('create-offline-account', name),
  signIn: () => invoke('sign-in'),
  signOut: id => invoke('sign-out', id),
  getAccountSkin: id => invoke('get-account-skin', id),
  getAccountCapes: id => invoke('get-account-capes', id),
  setAccountCape: (id, capeId) => invoke('set-account-cape', id, capeId),
  getRunningInstances: () => invoke('get-running-instances'),
  getGameLog: (profileId, instanceId, afterSeq) => invoke('get-game-log', profileId, instanceId, afterSeq),
  clearGameLog: (profileId, instanceId) => invoke('clear-game-log', profileId, instanceId),
  copyGameLog: (profileId, instanceId) => invoke('copy-game-log', profileId, instanceId),
  uploadGameLog: (profileId, instanceId) => invoke('upload-game-log', profileId, instanceId),
  play: (profileId, allowAdditional, versionId, serverAddress, serverPreference, worldId) => invoke('play', profileId, allowAdditional, versionId, serverAddress, serverPreference, worldId),
  install: versionId => invoke('install', versionId),
  deleteVersion: versionId => invoke('delete-version', versionId),
  chooseJava: () => invoke('choose-java'),
  getJavaRuntimes: () => invoke('get-java-runtimes'),
  deleteJavaRuntime: path => invoke('delete-java-runtime', path),
  openJavaLocation: path => invoke('open-java-location', path),
  createProfileShortcut: profileId => invoke('create-profile-shortcut', profileId),
  createVersionShortcut: versionId => invoke('create-version-shortcut', versionId),
  playVersion: (versionId, allowAdditional, serverAddress, serverPreference, temporaryOfflineName) => invoke('play-version', versionId, allowAdditional, serverAddress, serverPreference, temporaryOfflineName),
  importCustomClient: () => invoke('import-custom-client'),
  getWorlds: (profileId, refresh) => invoke('get-worlds', profileId, refresh),
  importWorld: profileId => invoke('import-world', profileId),
  renameWorld: (profileId, id, name) => invoke('rename-world', profileId, id, name),
  duplicateWorld: (profileId, id, name) => invoke('duplicate-world', profileId, id, name),
  deleteWorld: (profileId, id) => invoke('delete-world', profileId, id),
  resetWorldIcon: (profileId, id) => invoke('reset-world-icon', profileId, id),
  copyWorldSeed: (profileId, id) => invoke('copy-world-seed', profileId, id),
  openWorldFolder: (profileId, id) => invoke('open-world-folder', profileId, id),
  getServers: profileId => invoke('get-servers', profileId),
  reorderServers: (ids, profileId) => invoke('reorder-servers', ids, profileId),
  saveServer: (server, profileId) => invoke('save-server', server, profileId),
  deleteServer: (id, profileId) => invoke('delete-server', id, profileId),
  refreshServer: (id, profileId) => invoke('refresh-server', id, profileId),
  getProfileModsPath: id => invoke('get-profile-mods-path', id),
  openProfileMods: id => invoke('open-profile-mods', id),
  openVersionLocation: versionId => invoke('open-version-location', versionId),
  getErrorLog: () => invoke('get-error-log'),
  clearErrorLog: () => invoke('clear-error-log'),
  openErrorLog: () => invoke('open-error-log'),
  openFolder: profileId => invoke('open-folder', profileId),
  openSharedFolder: () => invoke('open-shared-folder'),
  chooseGameDirectory: () => invoke('choose-game-directory'),
  getScreenshots: (scope, offset, sort) => invoke('get-screenshots', scope, offset, sort),
  getScreenshot: id => invoke('get-screenshot', id),
  getScreenshotPreview: id => invoke('get-screenshot-preview', id),
  copyScreenshot: id => invoke('copy-screenshot', id),
  openScreenshotLocation: id => invoke('open-screenshot-location', id),
  deleteScreenshot: id => invoke('delete-screenshot', id),
  renameScreenshot: (id, name, confirmExtension) => invoke('rename-screenshot', id, name, confirmExtension),
  getDiskUsage: () => invoke('get-disk-usage'),
  getCleanupPreview: () => invoke('get-cleanup-preview'),
  cleanUnusedFiles: approvedPaths => invoke('clean-unused-files', approvedPaths),
  getOfflineStatus: () => invoke('get-offline-status'),
  getProviderStatus: () => invoke('get-provider-status'),
  connectCurseForge: key => invoke('connect-curseforge', key),
  getModCategories: (provider, type) => invoke('get-mod-categories', provider, type),
  searchMods: (query, gameVersion, loader, sort, offset, category, contentType, provider) => invoke('search-mods', query, gameVersion, loader, sort, offset, category, contentType, provider),
  getModProject: (id, provider) => invoke('get-mod-project', id, provider),
  getModVersions: (id, gameVersion, loader, provider, allGameVersions, contentType, refresh) => invoke('get-mod-versions', id, gameVersion, loader, provider, allGameVersions, contentType, refresh),
  getProfileContent: (profileId, kind) => invoke('get-profile-content', profileId, kind),
  setProfileContentEnabled: (profileId, kind, filename, enabled) => invoke('set-profile-content-enabled', profileId, kind, filename, enabled),
  installProfileContent: (profileId, kind, versionId, provider, content) => invoke('install-profile-content', profileId, kind, versionId, provider, content),
  checkProfileContentUpdates: (profileId, kind, force) => invoke('check-profile-content-updates', profileId, kind, force),
  revealProfileContent: (profileId, kind, filename) => invoke('reveal-profile-content', profileId, kind, filename),
  getContentIcon: url => invoke('get-content-icon', url),
  updateProfileContent: (profileId, kind, filename, content) => invoke('update-profile-content', profileId, kind, filename, content),
  getResourcePacks: profileId => invoke('get-resource-packs', profileId),
  setResourcePackEnabled: (profileId, filename, enabled) => invoke('set-resource-pack-enabled', profileId, filename, enabled),
  installResourcePack: (profileId, versionId, provider, content) => invoke('install-resource-pack', profileId, versionId, provider, content),
  installMod: (profileId, versionId, provider, content) => invoke('install-mod', profileId, versionId, provider, content),
  installModpack: (versionId, gameVersion, loader, provider, content) => invoke('install-modpack', versionId, gameVersion, loader, provider, content),
  installProfileModpack: (profileId, versionId, gameVersion, loader, target) => invoke('install-profile-modpack', profileId, versionId, gameVersion, loader, target),
  getSystemLogFiles: profileId => invoke('get-system-log-files', profileId),
  getSystemLog: (profileId, filename) => invoke('get-system-log', profileId, filename),
  deleteSystemLogs: (profileId, filenames) => invoke('delete-system-logs', profileId, filenames),
  copySystemLog: (profileId, filename) => invoke('copy-system-log', profileId, filename),
  uploadSystemLog: (profileId, filename) => invoke('upload-system-log', profileId, filename),
  getInstalledMods: profileId => invoke('get-installed-mods', profileId),
  getProfileMods: profileId => invoke('get-profile-mods', profileId),
  configureProfileVersion: (profileId, minecraftVersion, loader, acknowledged) => invoke('configure-profile-version', profileId, minecraftVersion, loader, acknowledged),
  installModLoader: (profileId, gameVersion, loader) => invoke('install-mod-loader', profileId, gameVersion, loader),
  openExternal: url => invoke('open-external', url),
  windowAction: action => invoke('window-action', action),
  on: <K extends keyof LauncherEvents>(event: K, listener: (value: LauncherEvents[K]) => void) => {
    const wrapped = (_: Electron.IpcRendererEvent, value: LauncherEvents[K]) => listener(value)
    ipcRenderer.on(`launcher:${event}`, wrapped)
    return () => ipcRenderer.removeListener(`launcher:${event}`, wrapped)
  }
}

contextBridge.exposeInMainWorld('launcher', api)
