#include <windows.h>
#include <wincrypt.h>
#include <shellapi.h>
#include <shlobj.h>
#include <shlwapi.h>
#include <string>
#include <vector>
#include <algorithm>
#ifndef CALG_SHA_256
#define CALG_SHA_256 0x800c
#endif
std::string utf8(const std::wstring&s){int n=WideCharToMultiByte(CP_UTF8,0,s.data(),s.size(),nullptr,0,nullptr,nullptr);std::string r(n,0);WideCharToMultiByte(CP_UTF8,0,s.data(),s.size(),&r[0],n,nullptr,nullptr);return r;}
std::string quoted(const std::wstring&s){std::string r="\"";for(char c:utf8(s)){if(c=='\\'||c=='\"')r+='\\';if((unsigned char)c<32)continue;r+=c;}return r+'\"';}
std::string read(const std::wstring&p){HANDLE f=CreateFileW(p.c_str(),GENERIC_READ,FILE_SHARE_READ|FILE_SHARE_WRITE|FILE_SHARE_DELETE,nullptr,OPEN_EXISTING,0,nullptr);if(f==INVALID_HANDLE_VALUE)return "";char b[4096];DWORD n;std::string r;while(ReadFile(f,b,sizeof(b),&n,nullptr)&&n)r.append(b,n);CloseHandle(f);return r;}
std::string hash(const std::wstring&p){HCRYPTPROV a=0;HCRYPTHASH h=0;HANDLE f=INVALID_HANDLE_VALUE;std::string result;if(!CryptAcquireContextW(&a,nullptr,nullptr,24,CRYPT_VERIFYCONTEXT))return result;if(!CryptCreateHash(a,CALG_SHA_256,0,0,&h))goto done;f=CreateFileW(p.c_str(),GENERIC_READ,FILE_SHARE_READ,nullptr,OPEN_EXISTING,0,nullptr);if(f==INVALID_HANDLE_VALUE)goto done;{std::vector<BYTE>b(1024*1024);DWORD n=0;while(ReadFile(f,b.data(),b.size(),&n,nullptr)&&n){if(!CryptHashData(h,b.data(),n,0))goto done;}BYTE d[32];n=32;if(!CryptGetHashParam(h,HP_HASHVAL,d,&n,0))goto done;for(auto c:d){const char*x="0123456789abcdef";result+=x[c>>4];result+=x[c&15];}}done:if(f!=INVALID_HANDLE_VALUE)CloseHandle(f);if(h)CryptDestroyHash(h);if(a)CryptReleaseContext(a,0);return result;}
void receipt(const std::wstring&p,const std::wstring&status,const std::wstring&from,const std::wstring&to,const std::wstring&target,DWORD error=0,bool logged=false){auto dir=p.substr(0,p.find_last_of(L"\\/"));SHCreateDirectoryExW(nullptr,dir.c_str(),nullptr);auto tmp=p+L".tmp";HANDLE f=CreateFileW(tmp.c_str(),GENERIC_WRITE,0,nullptr,CREATE_ALWAYS,0,nullptr);if(f==INVALID_HANDLE_VALUE)throw GetLastError();std::string s="{\"status\":"+quoted(status)+",\"from\":"+quoted(from)+",\"version\":"+quoted(to)+",\"target\":"+quoted(target)+",\"error\":"+std::to_string(error)+",\"logged\":"+(logged?"true":"false")+"}";DWORD n;bool ok=WriteFile(f,s.data(),s.size(),&n,nullptr)&&n==s.size();FlushFileBuffers(f);CloseHandle(f);if(!ok||!MoveFileExW(tmp.c_str(),p.c_str(),MOVEFILE_REPLACE_EXISTING|MOVEFILE_WRITE_THROUGH))throw GetLastError();}
bool failureLog(const std::wstring&record,DWORD error){
 auto p=record.substr(0,record.find_last_of(L"\\/"))+L"\\error-log.json";
 auto existing=read(p);if(existing.size()>2*1024*1024)return false;
 auto begin=existing.find_first_not_of(" \r\n\t"),end=existing.find_last_not_of(" \r\n\t");
 if(!existing.empty()&&(begin==std::string::npos||existing[begin]!='['||existing[end]!=']'))return false;
 SYSTEMTIME t;GetSystemTime(&t);char stamp[40];sprintf(stamp,"%04u-%02u-%02uT%02u:%02u:%02u.000Z",t.wYear,t.wMonth,t.wDay,t.wHour,t.wMinute,t.wSecond);
 std::string entry="{\"id\":\"update-"+std::string(stamp)+"\",\"at\":\""+stamp+"\",\"source\":\"Launcher güncellemesi\",\"code\":\"UPDATE_APPLY_FAILED\",\"message\":\"Güncelleme uygulanamadı. Windows hata kodu: "+std::to_string(error)+"\",\"level\":\"error\",\"count\":1}";
 std::string tail=existing.empty()?"":existing.substr(begin+1,end-begin-1);if(tail.find_first_not_of(" \r\n\t")!=std::string::npos)entry+=","+tail;
 entry="["+entry+"]";auto tmp=p+L".update-tmp";HANDLE f=CreateFileW(tmp.c_str(),GENERIC_WRITE,0,nullptr,CREATE_ALWAYS,0,nullptr);if(f==INVALID_HANDLE_VALUE)return false;DWORD n=0;bool ok=WriteFile(f,entry.data(),entry.size(),&n,nullptr)&&n==entry.size();FlushFileBuffers(f);CloseHandle(f);return ok&&MoveFileExW(tmp.c_str(),p.c_str(),MOVEFILE_REPLACE_EXISTING|MOVEFILE_WRITE_THROUGH);
}
bool launch(const std::wstring&p,HANDLE job,PROCESS_INFORMATION&pi){auto cmd=L"\""+p+L"\"";auto dir=p.substr(0,p.find_last_of(L"\\/"));STARTUPINFOW si{};si.cb=sizeof(si);if(!CreateProcessW(p.c_str(),&cmd[0],nullptr,nullptr,FALSE,CREATE_SUSPENDED|CREATE_NO_WINDOW,nullptr,dir.c_str(),&si,&pi))return false;if(!AssignProcessToJobObject(job,pi.hProcess)){TerminateProcess(pi.hProcess,1);CloseHandle(pi.hProcess);CloseHandle(pi.hThread);pi.hProcess=nullptr;return false;}ResumeThread(pi.hThread);CloseHandle(pi.hThread);return true;}
bool newer(const std::wstring&to,const std::wstring&from){unsigned a[3]{},b[3]{};if(swscanf(to.c_str(),L"%u.%u.%u",a,a+1,a+2)!=3||swscanf(from.c_str(),L"%u.%u.%u",b,b+1,b+2)!=3)return false;for(int i=0;i<3;i++)if(a[i]!=b[i])return a[i]>b[i];return false;}
int WINAPI WinMain(HINSTANCE,HINSTANCE,LPSTR,int){int argc=0;auto argv=CommandLineToArgvW(GetCommandLineW(),&argc);if(argc!=8)return 2;std::wstring target=argv[1],source=argv[2],record=argv[4],from=argv[5],version=argv[6],expected=argv[3];if(std::count(from.begin(),from.end(),L'.')==3)from=from.substr(0,from.find_last_of(L'.'));DWORD parent=wcstoul(argv[7],nullptr,10);LocalFree(argv);HANDLE mutex=CreateMutexW(nullptr,TRUE,L"Local\\GreenLauncherAtomicUpdate");if(GetLastError()==ERROR_ALREADY_EXISTS){CloseHandle(mutex);return 3;}auto candidate=target+L".update-new",backup=target+L".update-backup";HANDLE job=CreateJobObjectW(nullptr,nullptr);PROCESS_INFORMATION pi{};bool moved=false;DWORD error=0;try{if(!newer(version,from))throw DWORD(ERROR_REVISION_MISMATCH);if(PathIsRelativeW(target.c_str())||PathIsRelativeW(source.c_str())||PathIsRelativeW(record.c_str())||target==source||target.size()<4||target.substr(target.size()-4)!=L".exe"||expected.size()!=64||GetFileAttributesW(target.c_str())==INVALID_FILE_ATTRIBUTES)throw DWORD(ERROR_INVALID_PARAMETER);if(hash(source)!=utf8(expected))throw DWORD(ERROR_CRC);if(parent){HANDLE proc=OpenProcess(SYNCHRONIZE,FALSE,parent);if(proc){DWORD result=WaitForSingleObject(proc,60000);CloseHandle(proc);if(result==WAIT_TIMEOUT)throw DWORD(ERROR_TIMEOUT);}}if(!CopyFileW(source.c_str(),candidate.c_str(),FALSE))throw GetLastError();if(hash(candidate)!=utf8(expected))throw DWORD(ERROR_CRC);for(int i=0;i<300;i++){if(ReplaceFileW(target.c_str(),candidate.c_str(),backup.c_str(),REPLACEFILE_IGNORE_MERGE_ERRORS,nullptr,nullptr)){moved=true;break;}error=GetLastError();if(error!=ERROR_SHARING_VIOLATION&&error!=ERROR_ACCESS_DENIED)throw error;Sleep(200);}if(!moved)throw error;receipt(record,L"applied",from,version,target);if(!launch(target,job,pi))throw GetLastError();bool confirmed=false;for(int i=0;i<300;i++){if(read(record).find("\"confirmed\"")!=std::string::npos){confirmed=true;break;}Sleep(200);}if(!confirmed){TerminateJobObject(job,1);WaitForSingleObject(pi.hProcess,5000);throw DWORD(ERROR_TIMEOUT);}DeleteFileW(backup.c_str());DeleteFileW(source.c_str());CloseHandle(pi.hProcess);CloseHandle(job);ReleaseMutex(mutex);CloseHandle(mutex);return 0;}catch(DWORD code){error=code;}catch(...){error=ERROR_WRITE_FAULT;}if(pi.hProcess){TerminateJobObject(job,1);WaitForSingleObject(pi.hProcess,5000);CloseHandle(pi.hProcess);}if(moved){bool restored=false;for(int i=0;i<50;i++){if(MoveFileExW(backup.c_str(),target.c_str(),MOVEFILE_REPLACE_EXISTING|MOVEFILE_WRITE_THROUGH)){restored=true;break;}Sleep(200);}if(!restored)error=GetLastError();}try{receipt(record,L"failed",from,version,target,error,failureLog(record,error));DeleteFileW(candidate.c_str());}catch(...){}PROCESS_INFORMATION old{};launch(target,job,old);if(old.hProcess)CloseHandle(old.hProcess);CloseHandle(job);ReleaseMutex(mutex);CloseHandle(mutex);return 1;}
