const fs = require('node:fs'), path = require('node:path'), { createHash } = require('node:crypto'), { createRequire } = require('node:module'), assert = require('node:assert/strict')
const yaml = createRequire(require.resolve('electron-updater'))('js-yaml')
const pkg = require('../package.json'), release = path.join(__dirname, '..', 'release')
const latest = yaml.load(fs.readFileSync(path.join(release, 'latest.yml'), 'utf8'))
assert.equal(latest.version, pkg.version)
assert.equal(latest.files.length, 1)
const expected = `GreenLauncher-Setup-${pkg.version}.exe`, info = latest.files[0]
assert.equal(info.url, expected)
const bytes = fs.readFileSync(path.join(release, expected))
assert.equal(bytes.subarray(0, 2).toString(), 'MZ')
assert.equal(info.size, bytes.length)
assert.equal(info.sha512, createHash('sha512').update(bytes).digest('base64'))
assert.equal(latest.sha512, info.sha512)
assert.ok(fs.statSync(path.join(release, `${expected}.blockmap`)).size > 0)
// Notes now live on the GitHub release; legacy metadata may still include them.
assert.ok(latest.releaseNotes === undefined || typeof latest.releaseNotes === 'string')
const config = yaml.load(fs.readFileSync(path.join(release, 'win-unpacked', 'resources', 'app-update.yml'), 'utf8'))
assert.equal(config.provider, 'github'); assert.equal(config.owner, 'Despical'); assert.equal(config.repo, 'GreenLauncher'); assert.ok(!config.token)
assert.equal(pkg.build.nsis.deleteAppDataOnUninstall, false)
const portable=fs.readFileSync(path.join(release,`GreenLauncher-${pkg.version}.exe`)), metadata=JSON.parse(fs.readFileSync(path.join(release,'portable-update.json'),'utf8'))
assert.deepEqual({version:metadata.version,file:metadata.file,sha256:metadata.sha256,size:metadata.size},{version:pkg.version,file:`GreenLauncher-${pkg.version}.exe`,sha256:createHash('sha256').update(portable).digest('hex'),size:portable.length})
assert.ok(metadata.runtimeSize > portable.length)
assert.equal(metadata.blockmap.file, metadata.file + '.blocks.json')
const blockmapBytes=fs.readFileSync(path.join(release,metadata.blockmap.file))
assert.equal(metadata.blockmap.size,blockmapBytes.length)
assert.equal(metadata.blockmap.sha256,createHash('sha256').update(blockmapBytes).digest('hex'))
const {validateBlockMap}=require('./test-source.cjs').createSourceLoader()('src/main/update-blocks.ts')
validateBlockMap(JSON.parse(blockmapBytes.toString('utf8')),portable.length)
assert.equal(portable.subarray(0,2).toString(),'MZ')
assert.ok(fs.readFileSync(path.join(release,'win-unpacked/resources/update-helper.exe')).equals(fs.readFileSync(path.join(__dirname,'../build/update-helper.exe'))))
console.log(`PASS ${pkg.version} setup/portable EXEs, exact SHA-512/SHA-256 and sizes, both block maps, runtime size and token-free packaged GitHub update configuration`)
